### ISSUE TITLE
Setup toolbar and navigation system

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#1]
We have to agree upon a navigation design for the entire application. 

This task is completed when the application has a toolbar / navigation system that links to other pages / views.

**Comment by Mons1Oerjan** [comment]
Nav bar at the bottom

**Comment by ConnorWalsh7** [comment]
-Using a bottom navigation view for main app functions
-Created a main activity for tutors and main activity for students
-Each main activity has their own bottom navigation bar since tutors and students have different links
-Each link on the menu corresponds with a fragment instead of an activity
-TutorMainActivity and StudentMainActivity initialize the menu and place the appropriate fragments into the layout
-Added a bottom nav bar helper to disable the default 'shifting' if menu has more than 3 items
-Added links to the MainActivity screen to quickly jump to TutorMainActivity and StudentMainActivity for testing purposes
