### ISSUE TITLE
Fix profile picture upload bug

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#101]
The images don't show up in the listviews after taking a new picture. There's probably an issue with how we save and store the images.

**Comment by ConnorWalsh7** [comment]
Had a quick look into this. The default egg picture is loaded from res/drawable and is accessed differently than a stored image on the phone.  To load a stored image, like one saved after taking a picture for the profiles, you need to load it as a bitmap like this 
`Bitmap profile_pic = BitmapFactory.decodeFile(imageFileName);
image.setImageBitmap(profile_pic);`

I quickly tested this in the custom CursorAdapters we are using for our listviews and it works. However you can't load the default egg image this was because it's in the res/drawable folder. What we'll most likely need to do is change the seeders to have a null for profile pictures, so the CursorAdapters only attempt to replace the egg picture if a new profile picture was uploaded, otherwise the egg picture is set in the XML and it will show by default
