### ISSUE TITLE
Create tutor list view

### ISSUE THREAD

**Issue by ericdesj** [ericdesj/KRUSH#51]
The fragment for the tutor list already exist. This task involves creating a list view which gets populated by with the aforementioned fragment.

**Comment by Mons1Oerjan** [comment]
This task is for the following "minimum functionality" requirement:

Students can view a list of tutors given a university subject (minimum topics: Computer Science, Science, Math) and given a university.

Therefore, I will create the following components on the student's home fragment:
- A list of tutors. Clicking on an item in this list will bring the student to the tutor's profile page.
- A dropdown button containing subjects.

I think the student's university is set on the student's profile, so the list will already be filtered by university.

**Comment by Mons1Oerjan** [comment]
<img width="298" alt="screen shot 2017-03-11 at 2 10 47 am" src="https://cloud.githubusercontent.com/assets/16712579/23821183/36878450-0601-11e7-84da-be406f05e8f5.png">

## Current State
- I am getting all tutoring sessions for a student (currently using studentId = 1 until I can get the logged in user's id). 
- Displaying a list of `all` tutors. 
- `Rating = nul`l since no one has been rated yet. 
- Images are grabbed from the DB (I assigned dummy android images to everyone). 

## TODO
- We need to add timestamps to the tutoring sessions so I can query specifically for `upcoming` sessions, and not `all` sessions. 
- Need the logged in user's ID. 
- Need to improve the query so I can get the `location` of the upcoming session.

Let me know if you have any feedback.

**Comment by Mons1Oerjan** [comment]
See PR #62 

## Current State
![krush-1](https://cloud.githubusercontent.com/assets/16712579/23835842/0d390fe0-074d-11e7-9b5a-9722af963f20.gif)

## TODO
- Need to add timestamps to the tutoring sessions so I can query specifically for upcoming sessions, and not all sessions.
- Need the logged in user's ID.
- Need to improve the query so I can get the location of the upcoming session.
