### ISSUE TITLE
Student Payment Info TODO's

### ISSUE THREAD

**Issue by Mons1Oerjan** [ericdesj/KRUSH#88]
## TODO
- Pass tutorID, tutoringFee and studentID in the bundle
- Set the tutoring fee for the TextView
- Change temporary values in incrementTutorRevenue() method
- Determine what is the next intent - home view maybe?
- Remove available time

This task is dependent on the ability to book a tutoring session.

**Comment by ConnorWalsh7** [comment]
I passed all variables needed to create a session into the payment view since we would only want to create a session after a successful payment. I couldn't remove the tutors available time however, because we need to add the 'isBooked' variable to the availableTime table instead of the session table. Once the available time table has been updated we can fix this

**Comment by Mons1Oerjan** [comment]
dependent on PR #116

**Comment by ConnorWalsh7** [comment]
Final task of removing available time done in PR #143
